version: '3'

networks:
  common:

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=react-docker-app-prod
    ports:
      - 8888:80
    networks:
      - common
