version: '3'

networks:
  common:

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3030:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_NAME=react-docker-app
    volumes:
      - ./src:/app/src
    networks:
      - common
